default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: billbuddy
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: 127.0.0.1

development:
  <<: *default
  database: billbuddy_development

test:
  <<: *default
  database: billbuddy_test
production:
  <<: *default
  database: billbuddy_production
  username: billbuddy
  password: <%= ENV["DATABASE_PASSWORD"] %>
